services:
  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src/frontend/src:/usr/src/app/src
    depends_on:
      - backend
  backend:
    build:
      context: ./src/backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./src/backend:/usr/src/app/src
    